### PR TITLE
Restructured map.jinja, Added Support for OpenBSD and FreeBSD

### PR DESCRIPTION
**Pull request by 0xf10e**
Sorry, got a little bit messy with the branches here...

Wanted to add support for a FreeBSD NFS-server and OpenBSD NFS-client
but then had to add OS-specific defaults and thus restructure `map.jinja`...

Tested on FreeBSD 12-CURRENT (no big difference to 11.0 yet) as server & client
and a OpenBSD 5.9 client. NFSv3 in Free and Open seems pretty similar.

Not yet checked if I broke Linux but I can test tomorrow.

### CODE REVIEW

**Comment by 0xf10e** [comment]
Why not check @thomaslarsen's addition of RedHat while I'm at it?

**Comment by aboe76** [comment]
@0xf10e thanks for your configuration I have incorporated all in #25 to merge other PR's
are you ok with this?

**Comment by 0xf10e** [comment]
Sure!

**Comment by aboe76** [comment]
@0xf10e can we close this pr then?

**Pull request closed without merging**
