### PR TITLE
simplify map.jinja

### PR DESCRIPTION
**Pull request by aboe76**
fix issue with refactor an mappings.

### CODE REVIEW

**Comment by aboe76** [comment]
@javierbertoli this will fix the mapping issues I introduced.

**Comment by javierbertoli** [comment]
Definitely simpler :smile: 

Thanks, @aboe76

**Comment by mioux** [comment]
It's not working with debian server :

```
----------                
          ID: nfs-service 
    Function: service.running                       
        Name: nfs         
      Result: False       
     Comment: The named service nfs is not available                                                     
     Started: 18:55:19.104654                       
    Duration: 36.478 ms   
     Changes:     
```

The service is named nfs-server :smiley:

**Comment by wwentland** [comment]
I don't really like this change as it would result in various nested `grains.filter_by` calls for each grain that is being used. It's not inconceivable that one would like to incorporate settings based on, say, `osmajorrelease` or `osrelease`.

It also seems to drop the `:lookup` convention for overriding settings users don't typically want to set themselves and the change wouldn't be backward compatible.

By and large I like the earlier approach and would like to incorporate something similar in the template-formula. We might  be able to cut it down, but just because a specific instance is shorter, doesn't mean that the general approach is better.

**Pull request merged**
